-- Update data type in the flight table

ALTER TABLE flights
ALTER COLUMN airline VARCHAR(100) NOT NULL;
ALTER TABLE flights
ALTER COLUMN flight  VARCHAR(100) NOT NULL;
ALTER TABLE flights
ALTER COLUMN source_city  VARCHAR(100) NOT NULL;
ALTER TABLE flights
ALTER COLUMN departure_time VARCHAR(100) NOT NULL;
ALTER TABLE flights
ALTER COLUMN stops VARCHAR(100) NOT NULL;
ALTER TABLE flights
ALTER COLUMN arrival_time  VARCHAR(100) NOT NULL;
ALTER TABLE flights
ALTER COLUMN  destination_city VARCHAR(100)NOT NULL;
ALTER TABLE flights
ALTER COLUMN class  VARCHAR(100) NOT NULL;
ALTER TABLE flights
ALTER COLUMN class  VARCHAR(100) NOT NULL;
ALTER TABLE flights
ALTER COLUMN duration  DECIMAL(10,2) NOT NULL;
ALTER TABLE flights
ALTER COLUMN days_left  INTEGER NOT NULL;
ALTER TABLE flights
ALTER COLUMN days_left  INTEGER NOT NULL;
ALTER TABLE flights
ALTER COLUMN price  INTEGER NOT NULL;


  

 
  
  
 